config/routes.rb
Rails.application.routes.draw do
  resources :illustrations, only: :index
  resources :norms, only: :index
  resources :examples, only: :index
  devise_for :users
  root "users#index"
  resources :users, only: [:show]
  resources :books do
    member do
      get 'search'
    end
  end
  
  resources :books, only: [:new, :create, :show, :edit, :update, :destroy]

  resources :memos do
    member do
      get 'search'
    end
  end
  
  resources :books do
    resources :memos, only: [:new, :create, :show, :edit, :update, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :memos, dependent: :destroy

  validates :title, presence: true
end

app/models/memo.rb
class Memo < ApplicationRecord
  belongs_to :user
  belongs_to :book
  has_one_attached :image

  validates :image, presence: true
  validates :memo, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # has_many :user_books
  # has_many :books, through: :user_books
  has_many :books
  has_many :memos

  validates :name, presence: true

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  with_options presence: true, format: { with: PASSWORD_REGEX, message: 'Include both letters and numbers' } do
    validates :password
  end
end

app/models/user_book.rb
class UserBook < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameter, if: :devise_controller?

  private

  def configure_permitted_parameter
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :check_login
  before_action :title, only: [:show, :edit, :update, :destroy]

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to user_path(current_user)
    else
      render :new
    end
  end

  def show
    @memos = @book.memos.order('created_at DESC').page(params[:page]).per(3)
  end

  def edit
  end

  def update
    if @book.update(book_params)
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  def destroy
    if @book.destroy
      redirect_to user_path(current_user)
    else
      render :show
    end
  end

  def search
    @user = User.find(params[:id])
    @books = SearchBooksService.search(params[:keyword], @user).page(params[:page]).per(8)
  end

  private

  def book_params
    params.require(:book).permit(:title).merge(user_id: current_user.id)
  end

  def title
    @book = Book.find(params[:id])
  end

  def check_login
    redirect_to root_path unless user_signed_in?
  end
end

app/controllers/examples_controller.rb
class ExamplesController < ApplicationController
  def index
  end
end

app/controllers/illustrations_controller.rb
class IllustrationsController < ApplicationController
  def index
  end
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  before_action :check_login
  before_action :book, only: [:new, :create, :show, :edit, :update, :destroy]
  before_action :memo, only: [:show, :edit, :update, :destroy]

  def new
    @book = Book.find(params[:book_id])
    @memo = Memo.new
  end

  def create
    @memo = Memo.new(memo_params)
    if @memo.save
      redirect_to book_path(@memo.book)
    else
      render 'memos/new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @memo.update(memo_params)
      redirect_to book_memo_path(@book, @memo)
    else
      render :edit
    end
  end

  def destroy
    if @memo.destroy
      redirect_to book_path(@book)
    else
      render :show
    end
  end

  def search
    @book = Book.find(params[:id])
    @memos = SearchMemosService.search(params[:keyword], @book).page(params[:page]).per(3)
  end

  private

  def memo_params
    params.require(:memo).permit(:image, :memo).merge(user_id: current_user.id, book_id: params[:book_id])
  end

  def book
    @book = Book.find(params[:book_id])
  end

  def memo
    @memo = Memo.find(params[:id])
  end

  def check_login
    redirect_to root_path unless user_signed_in?
  end
end

app/controllers/norms_controller.rb
class NormsController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_login, only: :show
  before_action :user, only: :show

  def index
    redirect_to user_path(current_user.id) if user_signed_in?
  end

  def show
    @books = @user.books.page(params[:page]).per(8)
  end

  private

  def user
    @user = User.find(params[:id])
  end

  def check_login
    redirect_to root_path unless user_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/examples_helper.rb
module ExamplesHelper
end

app/helpers/illustrations_helper.rb
module IllustrationsHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/helpers/norms_helper.rb
module NormsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<%= render 'common/book-form', {info: "メモ一覧", path: book_path(@book), register: "編集"} %>

app/views/books/new.html.erb
<%= render 'common/book-form', {info: "マイページへ", path: user_path(current_user), register: "登録"} %>

app/views/books/search.html.erb
<%= render 'common/header' %>
<div class='main'>
  <div class='main-upper'>
    本一覧
  </div>
  <div class='main-lower'>
    <%# 本一覧表示 %>
    <ul class='book-list'>
      <% @books.each do |book| %>
        <li class='book'>
          <%= link_to book_path(book), class:'book-link' do %>
            <%= image_tag "/images/book_cover_kawa.png", class: "book-img" %>
            <div class='book-title'><%= book.title %></div>
          <% end %>
        </li>
      <% end %>
    </ul>

    <%# ページネーション %>
    <div class='paginate'>
      <%= paginate @books %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<header class='my-page-header'>
  <%# ヘッダー上部 %>
  <div class='search'>
    <%= render 'common/app-title' %>
    <%= render 'common/search-memo' %>
  </div>
  <%# ヘッダー下部 %>
  <div class='guide'>
    <%= render 'common/left-side-header', {info1: 'メモの追加', path1: new_book_memo_path(@book), info2: '本の編集', path2: edit_book_path(@book), info3: '本の削除', path3: book_path(@book)} %>
    <%= render 'common/right-side-header' %>
  </div>
</header>
<% if @memos.length != 0 %>
<div class='main'>
  <%# 本のタイトル表示 %>
  <%= render 'common/book-title', { title: @book.title} %>
  <div class='main-lower'>
    <%# メモ一覧表示 %>
    <ul class='memo-list'>
    <% @memos.each do |memo| %>
      <li class='memo'>
        <%= link_to book_memo_path(@book, memo) do %>
          <% if memo.image.attached? %>
            <%= image_tag memo.image, class: "memo-img" %>
          <% end %>
          <div class='memo-content'><%= memo.memo %></div>
        <% end %>
      </li>
    <% end %>
    </ul>
    
    <%# ページネーション %>
    <div class='paginate'>
      <%= paginate @memos %>
    </div>
  </div>
</div>
<%# メモが無いときのダミー %>
<% else %>
<div class='main'>
  <%# 本のタイトル表示 %>
  <%= render 'common/book-title', { title: @book.title} %>
  <div class='main-lower'>
    <%# メモ一覧表示 %>
    <ul class='memo-list'>
    <% 3.times do %>
      <li class='memo'>
        <%= link_to '#' do %>
          <%= image_tag '/images/1491.jpg', class: 'memo-img' %>
          <div class='memo-content'>メモを追加しよう</div>
        <% end %>
      </li>
    <% end %>
    </ul>
  </div>
</div>
<% end %>

app/views/common/_app-info.html.erb
<div class="left-page">
  <%= link_to 'ReadingMemo', '/', class: 'second-logo' %>
  <div class='introduction'>
    ReadingMemoは読書の際のメモを記録するためのアプリです。また、ユーザー同士でメモを共有することで新たな視点に気づくことができます。
  </div>
</div>

app/views/common/_app-title.html.erb
<div class='app-title'>
  ReadingMemo
</div>

app/views/common/_book-form.html.erb
<%# ヘッダー %>
<header class='my-page-header'>
  <div class='search'>
    <%= render 'common/app-title' %>
  </div>
  <div class='guide'>
   <div class='left-side-header'>
      <ul>
        <li>
          <%= link_to info, path , class: 'common-btn'%>
        </li>
      </ul>
    </div>
    <div class='right-side-header'>
      <ul>
        <li class='user-name'>
          <%= link_to current_user.name, user_path(current_user.id), class:'current-user'%>
        </li>
        <li>
          <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class:'logout' %>
        </li>
      </ul>
    </div>
  </div>
</header>

<%#本のタイトル入力フォーム %>
<div class='add-book'>
  <div class='main-content'>
    <div class='heading'>
      <div class='form-title'>
        <%= "タイトルの#{register}" %>
      </div>
    </div>
    <%= form_with model: @book, local: true, class: 'submit-form' do |f| %>
      <%# エラーメッセージの表示 %>
      <%= render 'common/error-messages', model: f.object %>
      
      <div class='label-cover'>
        <%= f.label :タイトル, class: 'book-title-label' %>
        <span class="required">必須</span>
      </div>
      <%= f.text_field :title, class: 'register-content', placeholder: 'タイトルを入力してください', maxlength: 30 %>
      <%= f.submit "本を#{register}", class: 'book-register' %>
    <% end %>
  </div>
</div>

app/views/common/_book-title.html.erb
<div class='main-upper'>
  <%= title %>
</div>

app/views/common/_error-messages.html.erb
<% if model.errors.any? %>
<div class='errors'>
  <ul class='errors-lists'>
    <% model.errors.full_messages.each do | message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/common/_examples-book.html.erb
<div class='index-lower-content'>
  <div class='index-main-lower'>
    <ul class='index-book-list'>
    <% titles = [{title: title1, path: path1}, {title: title2, path: path2}, {title: title3, path: path3}] %>
    <% titles.each do |title| %>
      <li class='index-book'>
        <%= link_to title[:path] do %>
          <%= image_tag "/images/book_cover_kawa.png", class: "index-book-img" %>
          <div class='index-book-title'><%= title[:title] %></div>
        <% end %>
      </li>
    <% end %>
    </ul>
  </div>
</div>

app/views/common/_examples-memo.html.erb
<%= render 'common/header' %>
<div class='main'>
  <%# 本のタイトル %>
  <div class='main-upper'>
    <%= title %>
  </div>
  <div class='main-lower'>
    <%# メモ一覧表示 %>
    <ul class='memo-list'>
      <li class='memo'>
        <%= image_tag "/images/IMG_30#{image1}.jpeg", class: "memo-img" %>
        <div class='memo-content'>
          <%= comment1 %>
        </div>
      </li>
      <li class='memo'>
        <%= image_tag "/images/IMG_30#{image2}.jpeg", class: "memo-img" %>
        <div class='memo-content'>
          <%= comment2 %>
        </div>
      </li>
    </ul>
  </div>
</div>

app/views/common/_examples.html.erb
<%= render 'common/header' %>
<div class='main'>
  <%# 本のタイトル %>
  <div class='main-upper'>
    <%= title %>
  </div>
  <div class='main-lower'>
    <%# メモ一覧表示 %>
    <ul class='memo-list'>
      <li class='memo'>
        <%= image_tag "/images/IMG_30#{image1}.jpeg", class: "memo-img" %>
        <div class='memo-content'>
          <%= comment1 %>
        </div>
      </li>
      <li class='memo'>
        <%= image_tag "/images/IMG_30#{image2}.jpeg", class: "memo-img" %>
        <div class='memo-content'>
          <%= comment2 %>
        </div>
      </li>
    </ul>
  </div>
</div>

app/views/common/_header.html.erb
<%# サインインしているときのヘッダー %>
<% if user_signed_in? %>
<header class='my-page-header'>
  <div class='search'>
    <%= render 'common/app-title' %>
    <%= form_with(url: search_book_path(@user), method: :get, class:'search-form', local: true) do |f|%>
      <%= f.text_field :keyword, placeholder:'本のタイトルを入力してください', class:'search-box' %>
      <%= f.submit '検索', class:'search-btn' %>
    <% end %>
  </div>
  <div class='guide'>
    <%= link_to '本の追加', new_book_path, class:'add-book-btn' %>
    <%= render 'common/right-side-header' %>
  </div>
</header>
<%# サインインしていないときのヘッダー %>
<% else %>
<header class='top-page-header'>
  <div class='top-header'>
    <div>
      <%= link_to 'ReadingMemo', root_path, class: 'app-title' %>
    </div>
    <div class='top-right-side-header'>
      <ul>
        <li>
          <%= link_to '新規登録', new_user_registration_path, class:'sign-up' %>
        </li>
        <li>
          <%= link_to 'ログイン', new_user_session_path, class:'log-in' %>
        </li>
      </ul>
    </div>
  </div>
</header>
<% end %>

app/views/common/_left-side-header.html.erb
<div class='left-side-header'>
  <ul>
    <li>
      <%= link_to info1, path1, class: 'common-btn' %>
      <%= link_to info2, path2 , class: 'common-btn' %>
      <%= link_to info3, path3, class: 'delete-book', method: :delete %>
    </li>
  </ul>
</div>

app/views/common/_memo-form.html.erb
<%# ヘッダー %>
<header class='my-page-header'>
  <div class='search'>
    <%= render 'common/app-title' %>
  </div>
  <div class='guide'>
   <div class='left-side-header'>
      <ul>
        <li>
          <%= link_to "メモ#{info}", path , class: 'common-btn'%>
        </li>
      </ul>
    </div>
    <%= render 'common/right-side-header' %>
  </div>
</header>

<%# メモ追加フォーム %>
<div class='add-memo'>
  <div class='add-memo-form'>
    <div class='heading'>
      <div class='form-title'>
        <%= "メモの#{str}" %>
      </div>
    </div>
    <%= form_with model: [@book, @memo], local: true, class: 'memo-form' do |f| %>
      <%# エラーメッセージの表示 %>
      <%= render 'common/error-messages', model: f.object %>
      
      <div class="img-upload">
        <div class="weight-bold-text">
          画像
          <span class="required">必須</span>
        </div>
        <div class="click-upload">
          <%= f.file_field :image, id:"item-image" %>
        </div>
      </div>
      <div class='label-cover'>
        <%= f.label :メモ, class: 'memo-label' %>
        <span class="required">必須</span>
      </div>
      <%= f.text_area :memo, class: 'memo-text', placeholder: 'メモを入力してください', rows: 8 %>
      <%= f.submit "メモを#{str}", class: 'memo-register-btn' %>
    <% end %>
  </div>
</div>

app/views/common/_right-side-header.html.erb
<div class='right-side-header'>
  <ul>
    <li class='user-name'>
      <%= link_to current_user.name, user_path(current_user.id), class:'current-user'%>
    </li>
    <li>
      <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class:'logout' %>
    </li>
  </ul>
</div>

app/views/common/_search-memo.html.erb
<%= form_with url: search_memo_path(@book), local: true, method: :get, class:'search-form'  do |f|%>
  <%= f.text_field :keyword, placeholder:'ワードを入力してください', class:'search-box' %>
  <%= f.submit '検索', class:'search-btn' %>
<% end %>

app/views/common/_second-header.html.erb
<div class="left-page">
  <%= link_to 'ReadingMemo', '/', class: 'second-logo' %>
  <div class='introduction'>
    ReadingMemoは紙の本に関するメモをまとめるためのアプリです。本にメモを結びつけることでメモを探す手間を省略することができます。
  </div>
</div>

app/views/examples/index.html.erb
<%= render 'common/examples-memo', { title: "Think clearly", comment1: "失敗しても、原因を突き止め改善することが大事。そうすることで、失敗で終わることはなくなる。失敗したままにすることが損になる。", comment2: "今生きていることこそが幸せ。高価なものを買えたり、大きい家に住むことでしか幸せを感じられないわけではない。幸せは日常にこそある。自分から見つけよう。", image1: 80, image2: 81} %>

app/views/illustrations/index.html.erb
<%= render 'common/examples-memo', { title: "嫌われる勇気", comment1: "目的論という言葉を初めて聞いた。言われてみれば、目的があって行動している。行動するときは目的を決める。", comment2: "行動するときに、一歩踏み出せないことがある。そういうときは今考えている課題が誰の課題なのか考える。課題の分離が行動するための力になる。", image1: 77, image2: 78} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReadingMemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/memos/edit.html.erb
<%= render 'common/memo-form', { info: "詳細", path: book_memo_path(@book, @memo), str: "編集"} %>

app/views/memos/new.html.erb
<%= render 'common/memo-form', { info: "一覧", path: book_path(@book), str: "登録"} %>

app/views/memos/search.html.erb
<header class='my-page-header'>
  <%# ヘッダー上部 %>
  <div class='search'>
    <%= render 'common/app-title' %>
    <%= render 'common/search-memo' %>
  </div>
  <%# ヘッダー下部 %>
  <div class='guide'>
    <div class='left-side-header'>
      <ul>
        <li>
          <%= link_to 'メモの追加', new_book_memo_path(@book), class: 'common-btn' %>
          <%= link_to '本の編集', edit_book_path(@book) , class: 'common-btn'%>
          <%= link_to '本の削除', book_path(@book), class: 'delete-book', method: :delete %>
        </li>
      </ul>
    </div>
    <%= render 'common/right-side-header' %>
  </div>
</header>

<div class='main'>
  <%# 本のタイトル表示 %>
  <div class='main-upper'>
    <%= @book.title %>
  </div>
  <div class='main-lower'>
    <%# メモ一覧表示 %>
    <ul class='memo-list'>
    <% @memos.each do |memo| %>
      <li class='memo'>
        <%= link_to book_memo_path(@book, memo) do %>
          <% if memo.image.attached? %>
            <%= image_tag memo.image.variant(resize: '250x500'), class: "memo-img" %>
          <% end %>
          <div class='memo-content'><%= memo.memo %></div>
        <% end %>
      </li>
    <% end %>
    </ul>

    <%# ページネーション %>
    <div class='paginate'>
      <%= paginate @memos %>
    </div>
  </div>
</div>

app/views/memos/show.html.erb
<header class='my-page-header'>
  <%# ヘッダー上部 %>
  <div class='search'>
    <%= render 'common/app-title' %>
  </div>
  <%# ヘッダー下部 %>
  <div class='guide'>
    <%= render 'common/left-side-header', {info1: 'メモ一覧', path1: book_path(@book), info2: 'メモの編集', path2: edit_book_memo_path(@book, @memo), info3: 'メモの削除', path3: book_memo_path(@book, @memo)} %>

    <%= render 'common/right-side-header' %>
  </div>
</header>

<div class='main'>
  <%# メモの表示 %>
  <div class='sub-main'>
    <div class='detail'>
      <% if @memo.image.attached? %>
        <%= image_tag @memo.image.variant(resize: '500x500'), class:'detail-img'%>
      <% end %>
      <div class='detail-memo'><%= @memo.memo %></div>
    </div>
  </div>
</div>

app/views/norms/index.html.erb
<%= render 'common/examples-memo', { title: "7つの習慣", comment1: "主体的とは、自ら行動し、その行動によって生じた結果に対して責任を持つこと。
主体的というと自ら行動することを指すと思っていたが、責任も持たなければいけない。責任を持つことを意識するとより自由度が上昇すると思う。", comment2: "関心の輪と影響の輪というものを初めて知った。日常を振り返ると結構関心の輪のことを考えていた。これからは今考えていることがどっちなのか考えるようにする。", image1: 74, image2: 73} %>

app/views/users/index.html.erb
<%= render 'common/header' %>
<%# アプリケーションの説明 %>
<div class='index-upper-content'>
  <div class='top-comment'>
    <span>
      より良い読書のためのメモ管理アプリ<br>
      ユーザー同士でメモを共有することで新たな視点に気づくことができます
    </span>
  </div>
</div>

<%# 例に出した本の表示 %>
<%= render 'common/examples-book', { title1: 'Think clearly', path1: examples_path, title2: '7つの習慣', path2: norms_path, title3: '嫌われる勇気', path3: illustrations_path} %>

app/views/users/show.html.erb
<%= render 'common/header' %>
<%#マイページでの本一覧の表示 %>
<% if @books.length != 0 %>
<div class='main'>
  <%= render 'common/book-title', { title: '本一覧'} %>
  <div class='main-lower'>
    <ul class='book-list'>
      <% @books.each do |book| %>
        <li class='book'>
          <%= link_to book_path(book), class:'book-link' do %>
            <%= image_tag "/images/book_cover_kawa.png", class: "book-img" %>
            <div class='book-title'><%= book.title %></div>
          <% end %>
        </li>
      <% end %>
    </ul>
    <%# ページネーション %>
    <div class='paginate'>
      <%= paginate @books %>
    </div>
  </div>
</div>
<%#本がない場合のダミー %>
<% else %>
<div class='main'>
  <%= render 'common/book-title', { title: '本を追加しよう!'} %>
  <div class='main-lower'>
    <ul class='book-list'>
    <% 8.times do %>
      <li class='book'>
        <%= link_to '#' do %>
          <%= image_tag "/images/book_cover_kawa.png", class: "book-img" %>
          <div class='book-title'>title</div>
        <% end %>
      </li>
    <% end %>
    </ul>
  </div>
</div>
<% end %>